# Danger: automating your team's conventions surrounding code review
# More info in Readme
name: Danger CI

on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled, unlabeled, review_requested, review_request_removed]

jobs:
  Danger:
    name: Run Danger JS
    runs-on: ubuntu-latest
    env:
      # As Danger uses a bot to put comments on your pr you need to
      # use `secrets.CI_BOT_TOKEN` (Personal Access Token) to provide write access to bot.
      DANGER_GITHUB_API_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      DANGER_DISABLE_TRANSPILATION: 'true'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Danger
        uses: danger/danger-js@11.0.2
